# Generated by Django 2.0.9 on 2018-10-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='richtextpage',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Leave blank for none.', null=True),
        ),
    ]
