# Generated by Django 2.0.9 on 2018-10-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20181011_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Leave blank for none.', null=True),
        ),
    ]
