# Generated by Django 2.0.9 on 2019-03-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_image_transcription_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
