# Generated by Django 2.0.13 on 2019-10-01 12:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('cms', '0011_image_essay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptionpage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='transcriptionpage',
            name='transcription',
        ),
        migrations.RemoveField(
            model_name='transcriptionpage',
            name='transcription_pdf',
        ),
        migrations.AddField(
            model_name='transcriptionpage',
            name='page_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='transcriptionpage',
            name='transcript',
            field=wagtail.core.fields.StreamField([('transcriptions', wagtail.documents.blocks.DocumentChooserBlock(icon='doc-full-inverse'))], blank=True),
        ),
    ]
